# Generated by Django 5.1.6 on 2025-03-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Technology", "Technology"),
                            ("Sports", "Sports"),
                            ("Education", "Education"),
                            ("Health", "Health"),
                        ],
                        max_length=255,
                    ),
                ),
                ("tags", models.JSONField(default=list)),
            ],
        ),
    ]
